version: "3.4"

services:
  dossarddb:
    container_name: dossarddb
    image: postgres:9.6-alpine
    env_file:
      - ./config/prod.env
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  api:
    container_name: api
    image: node:11.15.0-alpine
    working_dir: "/app"
    env_file:
      - ./config/dev.env
    volumes:
      - ./services/api:/app:delegated
    command: "npm run start:debug"
    ports:
      - "9090:9090"
      - "9229:9229"
  webapp:
    container_name: webapp
    image: node:11.15.0-alpine
    working_dir: "/app"
    volumes:
      - ./services/webapp:/app:delegated
    command: "npm start"
    ports:
      - "3000:3000"
volumes:
  postgres:
