services:
  dossarddb:
    container_name: dossarddb
    image: postgres:12-alpine3.20
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: dossarddb
      POSTGRES_USER: dossarduser
      POSTGRES_PASSWORD: dossardpwd
    ports:
      - "5432:5432"
  webapp:
    container_name: webapp
    environment:
      - NODE_ENV=development
    image: node:18-alpine
    working_dir: "/app"
    volumes:
      - ./services/webapp:/app
    command: "npm start"
    ports:
      - "3000:3000"
  api:
    container_name: api
    image: node:20-alpine
    working_dir: "/app"
    environment:
      POSTGRES_DB: dossarddb
      POSTGRES_USER: dossarduser
      POSTGRES_PASSWORD: dossardpwd
    volumes:
      - ./services/api:/app
    command: "npm run start:debug"
    ports:
      - "9090:9090"
      - "9229:9229"
volumes:
  postgres:
