version: "3.4"

services:
  dossarddb:
    container_name: dossarddb
    image: postgres:9.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    env_file:
      - ./config/dev.env
    ports:
      - "5432:5432"
  webapp:
    container_name: webapp
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    image: node:12-alpine
    working_dir: "/app"
    volumes:
      - ./services/webapp:/app:delegated
    command: "npm start"
    ports:
      - "3000:3000"
  api:
    container_name: api
    image: node:12-alpine
    working_dir: "/app"
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./services/api:/app
    command: "npm run start:debug"
    ports:
      - "9090:9090"
      - "9229:9229"
volumes:
  postgres:
