/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["AuthController_login_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["AuthController_refresh_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current user */
        post: operations["AuthController_logout_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["AuthController_getProfile_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/licences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all licences with pagination and filters */
        get: operations["LicencesController_findAll_v2"];
        put?: never;
        /** Create a new licence */
        post: operations["LicencesController_create_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/licences/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search licences by name or number (autocomplete) */
        get: operations["LicencesController_search_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/licences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get licence by ID */
        get: operations["LicencesController_findOne_v2"];
        put?: never;
        post?: never;
        /** Delete a licence */
        delete: operations["LicencesController_remove_v2"];
        options?: never;
        head?: never;
        /** Update a licence */
        patch: operations["LicencesController_update_v2"];
        trace?: never;
    };
    "/api/v2/licences/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import licences from CSV file */
        post: operations["LicencesController_importCsv_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all competitions with filters */
        get: operations["CompetitionsController_findAll_v2"];
        put?: never;
        /** Create a new competition */
        post: operations["CompetitionsController_create_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/competitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get competition by ID */
        get: operations["CompetitionsController_findOne_v2"];
        put?: never;
        post?: never;
        /** Delete a competition */
        delete: operations["CompetitionsController_remove_v2"];
        options?: never;
        head?: never;
        /** Update a competition */
        patch: operations["CompetitionsController_update_v2"];
        trace?: never;
    };
    "/api/v2/competitions/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate a competition */
        post: operations["CompetitionsController_duplicate_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/competitions/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate competition results */
        post: operations["CompetitionsController_validate_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/competitions/reorganize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorganize competition races */
        post: operations["CompetitionsController_reorganize_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all races with filters and pagination */
        get: operations["RacesController_findAll_v2"];
        put?: never;
        /** Engage a rider in a competition */
        post: operations["engage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/competition/{competitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all race entries for a competition with rider info */
        get: operations["getCompetitionRaces"];
        put?: never;
        post?: never;
        /** Delete all races for a competition */
        delete: operations["RacesController_removeByCompetition_v2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/palmares/{licenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get palmares (race history) for a rider */
        get: operations["getPalmares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/withpalmares/{query}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search licences that have at least one race in their palmares */
        get: operations["getLicencesWithPalmares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get race entry by ID */
        get: operations["RacesController_findOne_v2"];
        put?: never;
        post?: never;
        /** Delete a race entry (disengage rider) */
        delete: operations["deleteRace"];
        options?: never;
        head?: never;
        /** Update a race entry (generic) */
        patch: operations["RacesController_update_v2"];
        trace?: never;
    };
    "/api/v2/races/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create multiple race entries at once */
        post: operations["RacesController_createMany_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/refresh/{licenceId}/{competitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh engagement data from licence info */
        post: operations["refreshEngagement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update rider ranking (classify a rider) */
        put: operations["updateRanking"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/ranking/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Remove rider from ranking and reorder others */
        put: operations["removeRanking"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/ranking/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder rankings manually */
        put: operations["reorderRanking"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/{id}/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Toggle sprint challenge flag */
        put: operations["flagChallenge"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/{id}/chrono": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update rider chrono time */
        patch: operations["updateChrono"];
        trace?: never;
    };
    "/api/v2/races/{id}/tours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update rider lap count */
        patch: operations["updateTours"];
        trace?: never;
    };
    "/api/v2/races/results/upload/{competitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload race results from CSV file */
        post: operations["uploadResultsCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/races/competition/{competitionId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update race results in bulk for a competition */
        post: operations["RacesController_updateResults_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/clubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all clubs, optionally filtered by federation and department */
        get: operations["ClubsController_findAll_v2"];
        put?: never;
        /** Create a new club */
        post: operations["ClubsController_create_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/clubs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get club by ID */
        get: operations["ClubsController_findOne_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all challenges */
        get: operations["ChallengesController_findAll_v2"];
        put?: never;
        /** Create a new challenge */
        post: operations["ChallengesController_create_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/challenges/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get challenge by ID */
        get: operations["ChallengesController_findOne_v2"];
        put?: never;
        post?: never;
        /** Delete a challenge */
        delete: operations["ChallengesController_remove_v2"];
        options?: never;
        head?: never;
        /** Update a challenge */
        patch: operations["ChallengesController_update_v2"];
        trace?: never;
    };
    "/api/v2/challenges/{id}/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get challenge ranking */
        get: operations["ChallengesController_getRanking_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/challenges/{id}/competitions/{competitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a competition to a challenge */
        post: operations["ChallengesController_addCompetition_v2"];
        /** Remove a competition from a challenge */
        delete: operations["ChallengesController_removeCompetition_v2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary */
        get: operations["DashboardController_getSummary_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard statistics */
        get: operations["DashboardController_getStats_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recent activity */
        get: operations["DashboardController_getRecentActivity_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/charts/riders-per-competition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get riders count per competition */
        get: operations["DashboardController_getRidersPerCompetition_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/charts/club-participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get club participation stats */
        get: operations["DashboardController_getClubParticipation_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/charts/catea-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get age category distribution */
        get: operations["DashboardController_getCateaDistribution_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/charts/catev-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get value category distribution */
        get: operations["DashboardController_getCatevDistribution_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/dashboard/charts/top-riders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top 50 most active riders */
        get: operations["DashboardController_getTopRiders_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users with pagination (admin only) */
        get: operations["UsersController_findAll_v2"];
        put?: never;
        /** Create a new user (admin only) */
        post: operations["UsersController_create_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID (admin only) */
        get: operations["UsersController_findOne_v2"];
        put?: never;
        post?: never;
        /** Delete a user (admin only) */
        delete: operations["UsersController_remove_v2"];
        options?: never;
        head?: never;
        /** Update a user (admin only) */
        patch: operations["UsersController_update_v2"];
        trace?: never;
    };
    "/api/v2/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user password */
        patch: operations["UsersController_updatePassword_v2"];
        trace?: never;
    };
    "/api/v2/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset user password (admin only) */
        post: operations["UsersController_resetPassword_v2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
        };
        AuthResponseDto: {
            accessToken: string;
            refreshToken: string;
            user: {
                id: number;
                email: string;
                firstName: string;
                lastName: string;
                roles: string[];
            };
        };
        RefreshTokenDto: {
            refreshToken: string;
        };
        TokensDto: {
            accessToken: string;
            refreshToken: string;
        };
        CreateLicenceDto: {
            /** @example DUPONT */
            name: string;
            /** @example Jean */
            firstName: string;
            /** @example 12345678 */
            licenceNumber?: string;
            /**
             * @example H
             * @enum {string}
             */
            gender: "H" | "F";
            /** @example 1985 */
            birthYear: string;
            /** @example 31 */
            dept: string;
            /**
             * @example FSGT
             * @enum {string}
             */
            fede: "FSGT" | "UFOLEP" | "FFC" | "CYCLOS" | "FFVELO" | "NL" | "FFTRI";
            /** @example VC Toulouse */
            club?: string;
            /** @example Senior 1 */
            catea: string;
            /** @example 2ème catégorie */
            catev?: string;
            /** @example 2ème catégorie */
            catevCX?: string;
            /** @example 2024 */
            saison: string;
            comment?: string;
        };
        UpdateLicenceDto: {
            /** @example DUPONT */
            name?: string;
            /** @example Jean */
            firstName?: string;
            /** @example 12345678 */
            licenceNumber?: string;
            /**
             * @example H
             * @enum {string}
             */
            gender?: "H" | "F";
            /** @example 1985 */
            birthYear?: string;
            /** @example 31 */
            dept?: string;
            /**
             * @example FSGT
             * @enum {string}
             */
            fede?: "FSGT" | "UFOLEP" | "FFC" | "CYCLOS" | "FFVELO" | "NL" | "FFTRI";
            /** @example VC Toulouse */
            club?: string;
            /** @example Senior 1 */
            catea?: string;
            /** @example 2ème catégorie */
            catev?: string;
            /** @example 2ème catégorie */
            catevCX?: string;
            /** @example 2024 */
            saison?: string;
            comment?: string;
        };
        ClubEntity: {
            id: number;
            shortName?: string;
            longName: string;
            dept?: string;
            elicenceName?: string;
            /** @enum {string} */
            fede?: "FSGT" | "UFOLEP" | "FFC" | "CYCLOS" | "FFVELO" | "NL" | "FFTRI";
        };
        CompetitionEntity: {
            id: number;
            /** Format: date-time */
            eventDate: string;
            club?: components["schemas"]["ClubEntity"];
            clubId?: number;
            name?: string;
            zipCode: string;
            info?: string;
            categories: string;
            observations?: string;
            pricing?: Record<string, never>[];
            races: string;
            /** @enum {string} */
            fede: "FSGT" | "UFOLEP" | "FFC" | "CYCLOS" | "FFVELO" | "NL" | "FFTRI";
            /** @enum {string} */
            competitionType: "CX" | "ROUTE" | "VTT";
            competitionInfo?: Record<string, never>[];
            lieuDossard?: string;
            lieuDossardGPS?: string;
            longueurCircuit?: string;
            siteweb?: string;
            facebook?: string;
            contactEmail?: string;
            contactPhone?: string;
            contactName?: string;
            openedToOtherFede?: boolean;
            openedNL?: boolean;
            dept?: string;
            rankingUrl?: string;
            commissaires?: string;
            speaker?: string;
            aboyeur?: string;
            feedback?: string;
            resultsValidated?: boolean;
            photoUrls?: Record<string, never>[];
            rankingUrls?: Record<string, never>[];
            avecChrono?: boolean;
            registrationUrls?: Record<string, never>[];
        };
        ReorganizeCompetitionDto: {
            /** @description Competition ID */
            competitionId: number;
            /** @description New races configuration */
            races: string[];
        };
        RaceRowDto: {
            id: number;
            raceCode: string;
            catev: string;
            catea?: string;
            chrono?: string;
            tours?: number;
            riderNumber: number;
            rankingScratch?: number;
            numberMin?: number;
            numberMax?: number;
            licenceId: number;
            licenceNumber?: string;
            sprintchallenge?: boolean;
            comment?: string;
            competitionId: number;
            competitionName?: string;
            /** Format: date-time */
            competitionDate?: string;
            competitionType?: string;
            competitionRaces?: string[];
            /** @description Nom complet du coureur (NOM Prénom) */
            name: string;
            /** @description Nom du coureur seul */
            riderName?: string;
            club?: string;
            gender?: string;
            dept?: string;
            fede?: string;
            birthYear?: string;
            /** @description Coureur surclassé */
            surclassed?: boolean;
        };
        PalmaresRowDto: {
            id: number;
            raceCode: string;
            catev: string;
            catea?: string;
            chrono?: string;
            tours?: number;
            riderNumber: number;
            rankingScratch?: number;
            numberMin?: number;
            numberMax?: number;
            licenceId: number;
            licenceNumber?: string;
            sprintchallenge?: boolean;
            comment?: string;
            competitionId: number;
            competitionName?: string;
            /** Format: date-time */
            competitionDate?: string;
            competitionType?: string;
            competitionRaces?: string[];
            /** @description Nom complet du coureur (NOM Prénom) */
            name: string;
            /** @description Nom du coureur seul */
            riderName?: string;
            club?: string;
            gender?: string;
            dept?: string;
            fede?: string;
            birthYear?: string;
            /** @description Coureur surclassé */
            surclassed?: boolean;
            /** @description Classement dans la catégorie (calculé) */
            rankingInCategory?: number;
        };
        LicenceEntity: {
            id: number;
            licenceNumber?: string;
            name?: string;
            firstName?: string;
            gender?: string;
            club?: string;
            dept?: string;
            birthYear?: string;
            catea?: string;
            catev?: string;
            catevCX?: string;
            /** @enum {string} */
            fede: "FSGT" | "UFOLEP" | "FFC" | "CYCLOS" | "FFVELO" | "NL" | "FFTRI";
            saison?: string;
            author?: string;
            /** Format: date-time */
            lastChanged?: string;
            comment?: string;
        };
        RaceEntity: {
            id: number;
            competition?: components["schemas"]["CompetitionEntity"] | null;
            competitionId?: number;
            licence?: components["schemas"]["LicenceEntity"] | null;
            licenceId?: number;
            raceCode?: string | null;
            catev?: string | null;
            catea?: string | null;
            riderNumber?: number | null;
            rankingScratch?: number | null;
            numberMin?: number | null;
            numberMax?: number | null;
            surclassed?: boolean | null;
            comment?: string | null;
            sprintchallenge?: boolean | null;
            club?: string | null;
            chrono?: string | null;
            tours?: number | null;
        };
        CreateEngagementDto: {
            /** @description ID de la compétition */
            competitionId: number;
            /** @description ID de la licence du coureur */
            licenceId: number;
            /** @description Code de la course (ex: "1", "2/3") */
            raceCode: string;
            /** @description Numéro de dossard */
            riderNumber: number;
            /** @description Catégorie valeur (1, 2, 3, J, C, M...) */
            catev: string;
            /** @description Catégorie âge (S, V, SV, A...) */
            catea?: string;
            /** @description Club du coureur */
            club?: string;
            /** @description Classement scratch (si saisie résultats) */
            rankingScratch?: number;
        };
        UpdateRankingDto: {
            /** @description Numéro de dossard */
            riderNumber: number;
            /** @description Code de la course */
            raceCode: string;
            /** @description ID de la compétition */
            competitionId: number;
            /** @description Classement scratch */
            rankingScratch?: number;
            /** @description Commentaire (ABD, DSQ, NC, NP, CHT) */
            comment?: string;
        };
        RemoveRankingDto: {
            /** @description ID de l'engagement */
            id: number;
            /** @description Code de la course */
            raceCode: string;
            /** @description ID de la compétition */
            competitionId: number;
        };
        ReorderRankingItemDto: {
            /** @description ID de l'engagement */
            id: number;
            /** @description Commentaire (ABD, DSQ...) */
            comment?: string;
        };
        UpdateChronoDto: {
            /** @description Chrono au format HH:MM:SS ou MM:SS */
            chrono: string;
        };
        UpdateToursDto: {
            /** @description Nombre de tours */
            tours?: number;
        };
        ChallengeRaceRowDto: {
            /** @description Licence ID */
            licenceId: string;
            /** @description Competition ID */
            competitionId: number;
            /** @description Competition name */
            competitionName: string;
            /**
             * Format: date-time
             * @description Event date
             */
            eventDate: string;
            /** @description Category (catev) */
            catev: string;
            /** @description Ranking scratch */
            rankingScratch: number;
            /** @description Number of participants */
            nbParticipants: number;
            /** @description Race comment (DNF, DNS, etc.) */
            comment?: string;
            /** @description Sprint challenge bonus */
            sprintchallenge?: boolean;
            /** @description Points for this race */
            ptsRace?: number;
            /** @description Explanation of points calculation */
            explanation?: string;
        };
        ChallengeRiderDto: {
            /** @description Licence ID */
            licenceId: string;
            /** @description Last name */
            name: string;
            /** @description First name */
            firstName: string;
            /** @description Gender (H/F) */
            gender: string;
            /** @description Current licence catev */
            currentLicenceCatev: string;
            /** @description Current licence catea */
            currentLicenceCatea: string;
            /** @description Current club */
            currentClub: string;
            /** @description Sprint challenge status */
            sprintchallenge?: boolean;
            /** @description Race results */
            challengeRaceRows: components["schemas"]["ChallengeRaceRowDto"][];
            /** @description Total points for all races */
            ptsAllRaces: number;
            /** @description Explanation of total points calculation */
            explanation?: string;
        };
        ChallengeEntity: {
            id: number;
            name: string;
            description?: string;
            reglement?: string;
            active?: boolean;
            competitionIds?: number[];
            bareme?: string;
            competitionType?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Connexion impossible, vérifiez vos identifiants ou mot de passe */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensDto"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getProfile_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LicencesController_findAll_v2: {
        parameters: {
            query?: {
                /** @description Number of records to skip */
                offset?: number;
                /** @description Number of records to return */
                limit?: number;
                /** @description Global search term */
                search?: string;
                /** @description Field to order by */
                orderBy?: string;
                orderDirection?: "ASC" | "DESC";
                name?: string;
                firstName?: string;
                licenceNumber?: string;
                club?: string;
                dept?: string;
                /** @description Filter by federation */
                fede?: string;
                gender?: string;
                /** @description Filter by birth year */
                birthYear?: string;
                /** @description Filter by age category */
                catea?: string;
                /** @description Filter by value category */
                catev?: string;
                /** @description Filter by CX category */
                catevCX?: string;
                /** @description Filter by season */
                saison?: string;
                /** @description Filter by ID */
                id?: number;
                /** @description Filter licences without licence number */
                withoutNumber?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of licences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LicencesController_create_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLicenceDto"];
            };
        };
        responses: {
            /** @description Licence created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LicencesController_search_v2: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /** @description Competition type (CX, ROUTE) */
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of matching licences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LicencesController_findOne_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Licence ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Licence details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Licence not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LicencesController_remove_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Licence ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Licence deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Licence not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LicencesController_update_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Licence ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLicenceDto"];
            };
        };
        responses: {
            /** @description Licence updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Licence not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LicencesController_importCsv_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Import result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompetitionsController_findAll_v2: {
        parameters: {
            query?: {
                /** @description Number of records to skip */
                offset?: number;
                /** @description Number of records to return */
                limit?: number;
                /** @description Global search term */
                search?: string;
                /** @description Field to order by */
                orderBy?: string;
                orderDirection?: "ASC" | "DESC";
                /** @description Filter by name (partial match) */
                name?: string;
                /** @description Filter by zip code (partial match) */
                zipCode?: string;
                /** @description Filter by federation (partial match) */
                fede?: string;
                /** @description Filter by competition type (partial match) */
                competitionType?: string;
                /** @description Filter by department (partial match) */
                dept?: string;
                /** @description Filter by club name (partial match) */
                club?: string;
                /** @description Filter by multiple federations (comma-separated) */
                fedes?: string;
                /** @description Filter by multiple competition types (comma-separated) */
                competitionTypes?: string;
                /** @description Filter by multiple departments (comma-separated) */
                depts?: string;
                /** @description Show past competitions */
                displayPast?: boolean;
                /** @description Show future competitions */
                displayFuture?: boolean;
                /** @description Start date filter */
                startDate?: string;
                /** @description End date filter */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of competitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompetitionsController_create_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competition created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompetitionsController_findOne_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competition details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Competition not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompetitionsController_remove_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competition deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompetitionsController_update_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competition updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompetitionsController_duplicate_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competition duplicated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CompetitionsController_validate_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Results validated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionEntity"];
                };
            };
        };
    };
    CompetitionsController_reorganize_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorganizeCompetitionDto"];
            };
        };
        responses: {
            /** @description Races reorganized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RacesController_findAll_v2: {
        parameters: {
            query?: {
                /** @description Numéro de page */
                page?: number;
                /** @description Nombre d'éléments par page */
                limit?: number;
                /** @description ID de la compétition */
                competitionId?: number;
                /** @description ID de la licence */
                licenceId?: number;
                /** @description Code de la course */
                raceCode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of races */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    engage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEngagementDto"];
            };
        };
        responses: {
            /** @description Rider engaged */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceEntity"];
                };
            };
            /** @description Validation error (rider number taken, already registered) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCompetitionRaces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of races with rider information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceRowDto"][];
                };
            };
        };
    };
    RacesController_removeByCompetition_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Races deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPalmares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                licenceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of past races with rankings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PalmaresRowDto"][];
                };
            };
        };
    };
    getLicencesWithPalmares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Search query (name) */
                query: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of licences with palmares */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicenceEntity"][];
                };
            };
        };
    };
    RacesController_findOne_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Race details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceEntity"];
                };
            };
            /** @description Race not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteRace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Race deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RacesController_update_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Race updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RacesController_createMany_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Races created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshEngagement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                licenceId: number;
                competitionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Engagement refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceEntity"];
                };
            };
        };
    };
    updateRanking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRankingDto"];
            };
        };
        responses: {
            /** @description Ranking updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceEntity"];
                };
            };
        };
    };
    removeRanking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveRankingDto"];
            };
        };
        responses: {
            /** @description Ranking removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reorderRanking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRankingItemDto"][];
            };
        };
        responses: {
            /** @description Rankings reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    flagChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Challenge flag toggled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateChrono: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChronoDto"];
            };
        };
        responses: {
            /** @description Chrono updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTours: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateToursDto"];
            };
        };
        responses: {
            /** @description Tours updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadResultsCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Results uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid CSV format or data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RacesController_updateResults_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Results updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceEntity"][];
                };
            };
        };
    };
    ClubsController_findAll_v2: {
        parameters: {
            query?: {
                fede?: "FSGT" | "UFOLEP" | "FFC" | "CYCLOS" | "FFVELO" | "NL" | "FFTRI";
                dept?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of clubs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClubsController_create_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Club created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClubsController_findOne_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Club details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChallengesController_findAll_v2: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of challenges */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChallengesController_create_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Challenge created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChallengesController_findOne_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Challenge details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Challenge not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChallengesController_remove_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Challenge deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChallengesController_update_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Challenge updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChallengesController_getRanking_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Challenge ranking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeRiderDto"][];
                };
            };
        };
    };
    ChallengesController_addCompetition_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                competitionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competition added to challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeEntity"];
                };
            };
        };
    };
    ChallengesController_removeCompetition_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                competitionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competition removed from challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getSummary_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summary with stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getStats_v2: {
        parameters: {
            query?: {
                federation?: string;
                endDate?: string;
                startDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getRecentActivity_v2: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent competitions and races */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getRidersPerCompetition_v2: {
        parameters: {
            query?: {
                /** @description Start date filter */
                startDate?: string;
                /** @description End date filter */
                endDate?: string;
                /** @description Federations filter */
                fedes?: string[];
                /** @description Competition types filter */
                competitionTypes?: string[];
                /** @description Competition departments filter */
                competitionDepts?: string[];
                /** @description Rider departments filter */
                riderDepts?: string[];
                /** @description Clubs filter */
                clubs?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Riders per competition chart data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getClubParticipation_v2: {
        parameters: {
            query?: {
                /** @description Start date filter */
                startDate?: string;
                /** @description End date filter */
                endDate?: string;
                /** @description Federations filter */
                fedes?: string[];
                /** @description Competition types filter */
                competitionTypes?: string[];
                /** @description Competition departments filter */
                competitionDepts?: string[];
                /** @description Rider departments filter */
                riderDepts?: string[];
                /** @description Clubs filter */
                clubs?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Club participation chart data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getCateaDistribution_v2: {
        parameters: {
            query?: {
                /** @description Start date filter */
                startDate?: string;
                /** @description End date filter */
                endDate?: string;
                /** @description Federations filter */
                fedes?: string[];
                /** @description Competition types filter */
                competitionTypes?: string[];
                /** @description Competition departments filter */
                competitionDepts?: string[];
                /** @description Rider departments filter */
                riderDepts?: string[];
                /** @description Clubs filter */
                clubs?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Age category distribution chart data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getCatevDistribution_v2: {
        parameters: {
            query?: {
                /** @description Start date filter */
                startDate?: string;
                /** @description End date filter */
                endDate?: string;
                /** @description Federations filter */
                fedes?: string[];
                /** @description Competition types filter */
                competitionTypes?: string[];
                /** @description Competition departments filter */
                competitionDepts?: string[];
                /** @description Rider departments filter */
                riderDepts?: string[];
                /** @description Clubs filter */
                clubs?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Value category distribution chart data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getTopRiders_v2: {
        parameters: {
            query?: {
                /** @description Start date filter */
                startDate?: string;
                /** @description End date filter */
                endDate?: string;
                /** @description Federations filter */
                fedes?: string[];
                /** @description Competition types filter */
                competitionTypes?: string[];
                /** @description Competition departments filter */
                competitionDepts?: string[];
                /** @description Rider departments filter */
                riderDepts?: string[];
                /** @description Clubs filter */
                clubs?: string[];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top riders chart data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll_v2: {
        parameters: {
            query?: {
                /** @description Number of records to skip */
                offset?: number;
                /** @description Number of records to return */
                limit?: number;
                /** @description Global search term */
                search?: string;
                /** @description Field to order by */
                orderBy?: string;
                orderDirection?: "ASC" | "DESC";
                /** @description Filter by email */
                email?: string;
                /** @description Filter by first name */
                firstName?: string;
                /** @description Filter by last name */
                lastName?: string;
                /** @description Filter by phone */
                phone?: string;
                /** @description Filter by role */
                role?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updatePassword_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Password updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Current password is incorrect */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_resetPassword_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Password reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
