/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClubEntity,
    ClubEntityFromJSON,
    ClubEntityFromJSONTyped,
    ClubEntityToJSON,
    CompetitionInfo,
    CompetitionInfoFromJSON,
    CompetitionInfoFromJSONTyped,
    CompetitionInfoToJSON,
    FedeEnum,
    FedeEnumFromJSON,
    FedeEnumFromJSONTyped,
    FedeEnumToJSON,
    PricingInfo,
    PricingInfoFromJSON,
    PricingInfoFromJSONTyped,
    PricingInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CompetitionEntity
 */
export interface CompetitionEntity {
    /**
     * 
     * @type {Date}
     * @memberof CompetitionEntity
     */
    eventDate: Date;
    /**
     * 
     * @type {FedeEnum}
     * @memberof CompetitionEntity
     */
    fede: FedeEnum;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    competitionType: CompetitionEntityCompetitionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CompetitionEntity
     */
    id: number;
    /**
     * 
     * @type {ClubEntity}
     * @memberof CompetitionEntity
     */
    club: ClubEntity;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    zipCode: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    info?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionEntity
     */
    categories: Array<CompetitionEntityCategoriesEnum>;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    observations?: string;
    /**
     * 
     * @type {Array<PricingInfo>}
     * @memberof CompetitionEntity
     */
    pricing?: Array<PricingInfo>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionEntity
     */
    races?: Array<string>;
    /**
     * 
     * @type {Array<CompetitionInfo>}
     * @memberof CompetitionEntity
     */
    competitionInfo?: Array<CompetitionInfo>;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    localisation?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    gpsCoordinates: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    circuitLength?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    facebook?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    contactEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    contactPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    contactName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CompetitionEntity
     */
    isOpenedToOtherFede?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CompetitionEntity
     */
    isOpenedToNL?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    dept?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    rankingUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    commissioner?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    speaker?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    aboyeur?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    feedback?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CompetitionEntity
     */
    isValidInfos?: boolean;
}

export function CompetitionEntityFromJSON(json: any): CompetitionEntity {
    return CompetitionEntityFromJSONTyped(json, false);
}

export function CompetitionEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitionEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'eventDate': (new Date(json['eventDate'])),
        'fede': FedeEnumFromJSON(json['fede']),
        'competitionType': json['competitionType'],
        'id': json['id'],
        'club': ClubEntityFromJSON(json['club']),
        'name': json['name'],
        'zipCode': json['zipCode'],
        'info': !exists(json, 'info') ? undefined : json['info'],
        'categories': json['categories'],
        'observations': !exists(json, 'observations') ? undefined : json['observations'],
        'pricing': !exists(json, 'pricing') ? undefined : ((json['pricing'] as Array<any>).map(PricingInfoFromJSON)),
        'races': !exists(json, 'races') ? undefined : json['races'],
        'competitionInfo': !exists(json, 'competitionInfo') ? undefined : ((json['competitionInfo'] as Array<any>).map(CompetitionInfoFromJSON)),
        'localisation': !exists(json, 'localisation') ? undefined : json['localisation'],
        'gpsCoordinates': json['gpsCoordinates'],
        'circuitLength': !exists(json, 'circuitLength') ? undefined : json['circuitLength'],
        'website': !exists(json, 'website') ? undefined : json['website'],
        'facebook': !exists(json, 'facebook') ? undefined : json['facebook'],
        'contactEmail': !exists(json, 'contactEmail') ? undefined : json['contactEmail'],
        'contactPhone': !exists(json, 'contactPhone') ? undefined : json['contactPhone'],
        'contactName': !exists(json, 'contactName') ? undefined : json['contactName'],
        'isOpenedToOtherFede': !exists(json, 'isOpenedToOtherFede') ? undefined : json['isOpenedToOtherFede'],
        'isOpenedToNL': !exists(json, 'isOpenedToNL') ? undefined : json['isOpenedToNL'],
        'dept': !exists(json, 'dept') ? undefined : json['dept'],
        'rankingUrl': !exists(json, 'rankingUrl') ? undefined : json['rankingUrl'],
        'commissioner': !exists(json, 'commissioner') ? undefined : json['commissioner'],
        'speaker': !exists(json, 'speaker') ? undefined : json['speaker'],
        'aboyeur': !exists(json, 'aboyeur') ? undefined : json['aboyeur'],
        'feedback': !exists(json, 'feedback') ? undefined : json['feedback'],
        'isValidInfos': !exists(json, 'isValidInfos') ? undefined : json['isValidInfos'],
    };
}

export function CompetitionEntityToJSON(value?: CompetitionEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': (value.eventDate.toISOString()),
        'fede': FedeEnumToJSON(value.fede),
        'competitionType': value.competitionType,
        'id': value.id,
        'club': ClubEntityToJSON(value.club),
        'name': value.name,
        'zipCode': value.zipCode,
        'info': value.info,
        'categories': value.categories,
        'observations': value.observations,
        'pricing': value.pricing === undefined ? undefined : ((value.pricing as Array<any>).map(PricingInfoToJSON)),
        'races': value.races,
        'competitionInfo': value.competitionInfo === undefined ? undefined : ((value.competitionInfo as Array<any>).map(CompetitionInfoToJSON)),
        'localisation': value.localisation,
        'gpsCoordinates': value.gpsCoordinates,
        'circuitLength': value.circuitLength,
        'website': value.website,
        'facebook': value.facebook,
        'contactEmail': value.contactEmail,
        'contactPhone': value.contactPhone,
        'contactName': value.contactName,
        'isOpenedToOtherFede': value.isOpenedToOtherFede,
        'isOpenedToNL': value.isOpenedToNL,
        'dept': value.dept,
        'rankingUrl': value.rankingUrl,
        'commissioner': value.commissioner,
        'speaker': value.speaker,
        'aboyeur': value.aboyeur,
        'feedback': value.feedback,
        'isValidInfos': value.isValidInfos,
    };
}

/**
* @export
* @enum {string}
*/
export enum CompetitionEntityCompetitionTypeEnum {
    CX = 'CX',
    ROUTE = 'ROUTE',
    VTT = 'VTT',
    AUTRE = 'AUTRE'
}
/**
* @export
* @enum {string}
*/
export enum CompetitionEntityCategoriesEnum {
    _1ere = '1ere',
    _2eme = '2eme',
    _3eme = '3eme',
    _4eme = '4eme',
    _5eme = '5eme',
    Cadets = 'Cadets',
    Minimes = 'Minimes',
    Feminines = 'Feminines',
    Toutes = 'Toutes'
}


