/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompetitionInfo
 */
export interface CompetitionInfo {
    /**
     * 
     * @type {string}
     * @memberof CompetitionInfo
     */
    course: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionInfo
     */
    horaireEngagement: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionInfo
     */
    horaireDepart: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionInfo
     */
    info1: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionInfo
     */
    info2: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionInfo
     */
    info3: string;
}

export function CompetitionInfoFromJSON(json: any): CompetitionInfo {
    return CompetitionInfoFromJSONTyped(json, false);
}

export function CompetitionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitionInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'course': json['course'],
        'horaireEngagement': json['horaireEngagement'],
        'horaireDepart': json['horaireDepart'],
        'info1': json['info1'],
        'info2': json['info2'],
        'info3': json['info3'],
    };
}

export function CompetitionInfoToJSON(value?: CompetitionInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'course': value.course,
        'horaireEngagement': value.horaireEngagement,
        'horaireDepart': value.horaireDepart,
        'info1': value.info1,
        'info2': value.info2,
        'info3': value.info3,
    };
}


