/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompetitionIdsDTO
 */
export interface CompetitionIdsDTO {
    /**
     * 
     * @type {Array<number>}
     * @memberof CompetitionIdsDTO
     */
    ids?: Array<number>;
}

export function CompetitionIdsDTOFromJSON(json: any): CompetitionIdsDTO {
    return CompetitionIdsDTOFromJSONTyped(json, false);
}

export function CompetitionIdsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitionIdsDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ids': !exists(json, 'ids') ? undefined : json['ids'],
    };
}

export function CompetitionIdsDTOToJSON(value?: CompetitionIdsDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ids': value.ids,
    };
}


