/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClubEntity,
    ClubEntityFromJSON,
    ClubEntityFromJSONTyped,
    ClubEntityToJSON,
} from './';

/**
 * 
 * @export
 * @interface CompetitionEntity
 */
export interface CompetitionEntity {
    /**
     * 
     * @type {number}
     * @memberof CompetitionEntity
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CompetitionEntity
     */
    eventDate: Date;
    /**
     * 
     * @type {ClubEntity}
     * @memberof CompetitionEntity
     */
    club: ClubEntity;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    zipCode: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    info?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionEntity
     */
    categories: Array<CompetitionEntityCategoriesEnum>;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    observations?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionEntity
     */
    pricing?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionEntity
     */
    races?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    fede: CompetitionEntityFedeEnum;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    competitionType?: CompetitionEntityCompetitionTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionEntity
     */
    competitionInfo?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    lieuDossard?: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    lieuDossardGPS: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    longueurCircuit: string;
}

export function CompetitionEntityFromJSON(json: any): CompetitionEntity {
    return CompetitionEntityFromJSONTyped(json, false);
}

export function CompetitionEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitionEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'eventDate': (new Date(json['eventDate'])),
        'club': ClubEntityFromJSON(json['club']),
        'name': json['name'],
        'zipCode': json['zipCode'],
        'info': !exists(json, 'info') ? undefined : json['info'],
        'categories': json['categories'],
        'observations': !exists(json, 'observations') ? undefined : json['observations'],
        'pricing': !exists(json, 'pricing') ? undefined : json['pricing'],
        'races': !exists(json, 'races') ? undefined : json['races'],
        'fede': json['fede'],
        'competitionType': !exists(json, 'competitionType') ? undefined : json['competitionType'],
        'competitionInfo': !exists(json, 'competitionInfo') ? undefined : json['competitionInfo'],
        'lieuDossard': !exists(json, 'lieuDossard') ? undefined : json['lieuDossard'],
        'lieuDossardGPS': json['lieuDossardGPS'],
        'longueurCircuit': json['longueurCircuit'],
    };
}

export function CompetitionEntityToJSON(value?: CompetitionEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'eventDate': (value.eventDate.toISOString()),
        'club': ClubEntityToJSON(value.club),
        'name': value.name,
        'zipCode': value.zipCode,
        'info': value.info,
        'categories': value.categories,
        'observations': value.observations,
        'pricing': value.pricing,
        'races': value.races,
        'fede': value.fede,
        'competitionType': value.competitionType,
        'competitionInfo': value.competitionInfo,
        'lieuDossard': value.lieuDossard,
        'lieuDossardGPS': value.lieuDossardGPS,
        'longueurCircuit': value.longueurCircuit,
    };
}

/**
* @export
* @enum {string}
*/
export enum CompetitionEntityCategoriesEnum {
    _1ere = '1ere',
    _2eme = '2eme',
    _3eme = '3eme',
    _4eme = '4eme',
    _5eme = '5eme',
    Cadets = 'Cadets',
    Minimes = 'Minimes',
    Feminines = 'Feminines'
}
/**
* @export
* @enum {string}
*/
export enum CompetitionEntityFedeEnum {
    FSGT = 'FSGT',
    UFOLEP = 'UFOLEP',
    FFC = 'FFC',
    NL = 'NL'
}
/**
* @export
* @enum {string}
*/
export enum CompetitionEntityCompetitionTypeEnum {
    CX = 'CX',
    ROUTE = 'ROUTE',
    VTT = 'VTT',
    Empty = ''
}


