/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompetitionReorganize
 */
export interface CompetitionReorganize {
    /**
     * 
     * @type {number}
     * @memberof CompetitionReorganize
     */
    competitionId?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionReorganize
     */
    races?: Array<string>;
}

export function CompetitionReorganizeFromJSON(json: any): CompetitionReorganize {
    return CompetitionReorganizeFromJSONTyped(json, false);
}

export function CompetitionReorganizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompetitionReorganize {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'competitionId': !exists(json, 'competitionId') ? undefined : json['competitionId'],
        'races': !exists(json, 'races') ? undefined : json['races'],
    };
}

export function CompetitionReorganizeToJSON(value?: CompetitionReorganize | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'competitionId': value.competitionId,
        'races': value.races,
    };
}


