/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum FedeEnum {
    FSGT = 'FSGT',
    UFOLEP = 'UFOLEP',
    FFC = 'FFC',
    CYCLOS = 'CYCLOS',
    FFVELO = 'FFVELO',
    FFTRI = 'FFTRI',
    NL = 'NL'
}

export function FedeEnumFromJSON(json: any): FedeEnum {
    return FedeEnumFromJSONTyped(json, false);
}

export function FedeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FedeEnum {
    return json as FedeEnum;
}

export function FedeEnumToJSON(value?: FedeEnum | null): any {
    return value as any;
}

