/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RaceFilter
 */
export interface RaceFilter {
    /**
     * 
     * @type {Array<number>}
     * @memberof RaceFilter
     */
    competitionIds?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof RaceFilter
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceFilter
     */
    catev?: string;
}

export function RaceFilterFromJSON(json: any): RaceFilter {
    return RaceFilterFromJSONTyped(json, false);
}

export function RaceFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): RaceFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'competitionIds': !exists(json, 'competitionIds') ? undefined : json['competitionIds'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'catev': !exists(json, 'catev') ? undefined : json['catev'],
    };
}

export function RaceFilterToJSON(value?: RaceFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'competitionIds': value.competitionIds,
        'gender': value.gender,
        'catev': value.catev,
    };
}


