/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RaceNbRider
 */
export interface RaceNbRider {
    /**
     * 
     * @type {Date}
     * @memberof RaceNbRider
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof RaceNbRider
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof RaceNbRider
     */
    raceCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceNbRider
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceNbRider
     */
    fede?: string;
}

export function RaceNbRiderFromJSON(json: any): RaceNbRider {
    return RaceNbRiderFromJSONTyped(json, false);
}

export function RaceNbRiderFromJSONTyped(json: any, ignoreDiscriminator: boolean): RaceNbRider {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'count': !exists(json, 'count') ? undefined : json['count'],
        'raceCode': !exists(json, 'raceCode') ? undefined : json['raceCode'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'fede': !exists(json, 'fede') ? undefined : json['fede'],
    };
}

export function RaceNbRiderToJSON(value?: RaceNbRider | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'count': value.count,
        'raceCode': value.raceCode,
        'name': value.name,
        'fede': value.fede,
    };
}


