/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RaceCreate
 */
export interface RaceCreate {
    /**
     * 
     * @type {number}
     * @memberof RaceCreate
     */
    competitionId?: number;
    /**
     * 
     * @type {number}
     * @memberof RaceCreate
     */
    licenceId?: number;
    /**
     * 
     * @type {number}
     * @memberof RaceCreate
     */
    riderNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof RaceCreate
     */
    raceCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceCreate
     */
    catev?: string;
}

export function RaceCreateFromJSON(json: any): RaceCreate {
    return RaceCreateFromJSONTyped(json, false);
}

export function RaceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RaceCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'competitionId': !exists(json, 'competitionId') ? undefined : json['competitionId'],
        'licenceId': !exists(json, 'licenceId') ? undefined : json['licenceId'],
        'riderNumber': !exists(json, 'riderNumber') ? undefined : json['riderNumber'],
        'raceCode': !exists(json, 'raceCode') ? undefined : json['raceCode'],
        'catev': !exists(json, 'catev') ? undefined : json['catev'],
    };
}

export function RaceCreateToJSON(value?: RaceCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'competitionId': value.competitionId,
        'licenceId': value.licenceId,
        'riderNumber': value.riderNumber,
        'raceCode': value.raceCode,
        'catev': value.catev,
    };
}


