/* tslint:disable */
/* eslint-disable */
/**
 * Open Dossard
 * Documentation de l\'API Open Dossard
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@opendossard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Filter,
    FilterFromJSON,
    FilterFromJSONTyped,
    FilterToJSON,
} from './';

/**
 * 
 * @export
 * @interface Search
 */
export interface Search {
    /**
     * 
     * @type {number}
     * @memberof Search
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof Search
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof Search
     */
    orderDirection?: string;
    /**
     * 
     * @type {string}
     * @memberof Search
     */
    orderBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Search
     */
    search?: string;
    /**
     * 
     * @type {Array<Filter>}
     * @memberof Search
     */
    filters?: Array<Filter>;
}

export function SearchFromJSON(json: any): Search {
    return SearchFromJSONTyped(json, false);
}

export function SearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Search {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentPage': !exists(json, 'currentPage') ? undefined : json['currentPage'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'orderDirection': !exists(json, 'orderDirection') ? undefined : json['orderDirection'],
        'orderBy': !exists(json, 'orderBy') ? undefined : json['orderBy'],
        'search': !exists(json, 'search') ? undefined : json['search'],
        'filters': !exists(json, 'filters') ? undefined : ((json['filters'] as Array<any>).map(FilterFromJSON)),
    };
}

export function SearchToJSON(value?: Search | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentPage': value.currentPage,
        'pageSize': value.pageSize,
        'orderDirection': value.orderDirection,
        'orderBy': value.orderBy,
        'search': value.search,
        'filters': value.filters === undefined ? undefined : ((value.filters as Array<any>).map(FilterToJSON)),
    };
}


