export enum Category {
  PREMIERE = 'PREMIERE',
  SECONDE = 'SECONDE',
  TROISIEME = 'TROISIEME',
  QUATRIEME = 'QUATRIEME',
  CINQUIEME = 'CINQUIEME',
  CADETS = 'CADETS',
  MINIMES = 'MINIMES',
  FEMININES = 'FEMININES',
  TOUTES = 'TOUTES',
}
