INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (117, 'TOAC Cyclisme', null, 'TOAC');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (5, 'Association Espoir Cyclo Ognes', null, 'AECO');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (2, 'Cyclo Club Castanéen', '31', 'CCC31');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (3, 'Roquette Cyclo Club', '31', 'VCRO');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (4, 'La Roue Carrée Montjovienne (Montjoire)', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (8, 'Union Sportive Vacquiers', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (11, 'Association Union Cyclo-Capdenac', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (13, 'Saint-Juéry Olympique Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (14, 'Couserans Cycliste', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (18, 'Vélo Club Sundgovia Altkirch', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (19, 'Gourdan Polignan Comminges Cycliste', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (20, 'Association L''Alternative VTT', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (21, 'Union Sportive Fronton Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (22, 'Vittel Triathlon', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (23, 'Vélo Sprint Narbonnais', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (24, 'Cyclosport Casteljaloux', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (25, 'Team ATC Donzère', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (26, 'Avenir Cyclisme Bastidien (Labastide du Tarn)', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (28, 'Tolosa Cycling Team', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (30, 'Cyclo-Club Castanéen', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (31, 'Association Sportive Villemur Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (32, 'Roue Libre Saman', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (33, 'Cycling Team Black Devil', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (34, 'Equipe CMI', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (35, 'Longages Espoir Cycliste', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (36, 'Union Sportive Aviation Latécoère', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (37, 'Vélo-Club Avranches', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (38, 'Montauban Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (39, 'Amicale Cyclo Escalquens', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (40, 'Empalot Vélo-Club', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (41, 'Cercle Athlétique Castelsarrasinois Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (42, 'Saint-Gaudens Cyclisme Comminges', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (43, 'Vélo-Club Blayais', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (44, 'Balma Vélo-Sprint', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (45, 'Camarade Sports & Loisirs', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (46, 'Association Couserans Cycliste', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (47, 'Association Sportive et Culturelle Gagnac Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (48, 'Association Cyclisme Clapiers', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (49, 'Association Sportive des Autobus Toulousains', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (50, 'Centre Sportif Omnisports Ariègeois 09', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (51, 'Espagne', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (52, 'Association Bicyclettes 09', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (53, 'Etoile Sportive Gimont Cyclo', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (54, 'Vélo-Club Saint-Cyprien', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (55, 'Villeneuve Cycliste', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (56, 'Union Sportive Colomiers Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (57, 'Teyran Bike 34', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (58, 'Team Montagnac Avenir Cycliste', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (59, 'Association Guidon Verdunois', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (60, 'Cyclo-Club Mazérien', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (61, 'Association Foyer Jeunes Education', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (62, 'Sorèze Vélo-Club', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (63, 'Union Cycliste Tullins', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (64, 'Comité FSGT 82', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (66, 'L''Union Cycliste 31', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (67, 'Revel Sprinter-Club', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (68, 'Team Master Pro 82', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (69, 'Mirebeau Sport Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (71, 'Vélo-Club du Velay', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (72, 'Balma Olympique Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (73, 'Team Exper''Cycle', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (74, 'Team Sud Vélo Montpellier', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (76, 'Cyclo-Club Léguevin', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (77, 'Plaisance du Touch Amicale Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (78, 'Toulouse Université Club Triathlon', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (79, 'Avenir Cycliste Auterivain', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (80, 'Association Sportive Carcassonne Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (81, 'Comité FSGT 81', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (82, 'Cyclo Salvetain (La Salvetat Saint Gilles)', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (83, 'Montréjeau Cyclo-Club', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (84, 'Vélo D''Alcas', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (85, 'Cyclo Fonsorbais', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (86, 'NL', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (87, 'Union Sportive Madinina Gwada', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (88, 'Vélo-Club Cambonnais', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (89, 'Bruguières Vélo-Club', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (90, 'Guidon Sportif Coursan/Narbonne', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (91, 'Thales Inter Sports', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (92, 'Entente Cycliste Osny-Pontoise', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (93, 'Vélo-Sport Castrais', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (94, 'UV Auch GG', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (95, 'Vélo-Club Villefranchois', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (96, 'Saint-Chély d''Apcher Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (97, 'Association des Sapeurs Pompiers de l''Hérault Montpellier', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (98, 'Vélo Club Mondonvillois', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (99, 'Union Sportive Plaisance Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (100, 'Association Saint-Nauphary Vélo Sport', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (101, 'ASPTT Gaillac Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (102, 'Vélo-Sport Léo Lagrange Castres', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (103, 'Cyclo-Club Bédarieux', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (104, 'Cyclo-Club Toulouse Lardenne', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (105, 'Comité Départemental 32', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (106, 'Guidon Verdunois', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (107, 'Avenir Cycliste Rabastinois', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (108, 'Grupetto Club', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (109, 'Centre Sportif Omnisport Ariègeois 09', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (110, 'Amicale Cycliste Tournefeuille', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (111, 'Beziers Méditérranée Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (112, 'Club Cycliste Le Boulou', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (113, 'Etoile Cycliste Bastiaise', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (114, 'Béziers Méditerranée Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (115, 'Guidon Fuxeen', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (116, 'Club Olympique Carbonnais Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (118, 'Canohes Avenir Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (119, 'Team Jallet Auto', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (120, 'Comité FSGT 31', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (121, 'Vélo-Sport Castelnaudary', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (122, 'Guidon Sprinter Club de  Blagnac', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (123, 'Team Ariège Cycles', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (124, 'Union Sportive Castelsagrat Cyclisme', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (125, 'Vélo-Club Larra', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (126, 'Union Vélocipédique Mazamétaine', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (127, 'Vélo-Club CPRS Pins-Justaret/Vilatte', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (128, 'Vélo-Club les 3 C', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (129, 'Albi Vélo-Sport', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (130, 'Lavaur Vélo-Club', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (131, 'Fonbeauzard Vélo-Club', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (6, 'Romilly Sports 10', null, 'ROMILLY');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (7, 'Vertical Bike Muret', null, 'VERTICAL');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (9, 'Association Cycliste Le Fousseret', null, 'ACF');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (10, 'Vélo-Club Mauvezinois', null, 'VCM');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (12, 'Castelmayran Vélo Club', null, 'CVC');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (15, 'Cyclo-Club des Violettes Castelmauroux', null, 'CCVC');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (16, 'Vélo-Club Roquettois Omnisports', null, 'VCRO');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (17, 'JT Cycles Racing', null, 'JTCR');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (27, 'Vélo Occitan Club', null, 'VELOC');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (29, 'Association Sportive Muret Cyclisme', null, 'ASMC');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (65, 'Clarac Comminges Cyclisme', null, 'CLARAC');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (70, 'La Pancarte', null, 'PANCARTE');
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (132, 'Vélo-Sport Saint-Affrique', null, null);
INSERT INTO public.club (id, "longName", dept, "shortName") VALUES (75, 'TUC Triathlon', null, 'TUC');
