INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (1, 'Grand Prix de Saint-Julien', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-03-17 12:38:23.616000', 'FSGT', 2, '31220', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (2, 'Tour du Canton de Launac', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-03-24 12:38:23.616000', 'FSGT', 2, '31330', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (3, 'Cap Découverte', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-03-31 12:38:23.616000', 'FSGT', 2, '81450', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (4, 'Grand Prix de Saint-Thomas', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-04-07 12:38:23.616000', 'FSGT', 2, '31470', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (5, 'Grand Prix de Castelsagrat', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-04-14 12:38:23.616000', 'FSGT', 2, '82400', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (6, 'Grand Prix de Lussan-Adeilhac', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-04-27 12:38:23.616000', 'FSGT', 2, '31430', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (7, 'La Classique Aussonne-Aussonne', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-04-28 12:38:23.616000', 'FSGT', 2, '31840', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (8, 'Grand Prix du Muguet à Balma', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-05-01 12:38:23.616000', 'FSGT', 2, '31130', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (9, 'Grand Prix de Sayrac', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-05-20 12:38:23.616000', 'FSGT', 2, '31340', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (10, 'Grand Prix de Castelnau d''Estretefonds', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-05-26 12:38:23.616000', 'FSGT', 2, '31620', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (11, 'Grand Prix de Villematier', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-05-30 12:38:23.616000', 'FSGT', 2, '31340', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (12, 'Championnat Haute Garonne 2019 à Bazus', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-06-02 12:38:23.616000', 'FSGT', 2, '31380', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (13, 'La Ronde Carla-Bayle - Etape 1', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-06-08 12:38:23.616000', 'FSGT', 2, '09130', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (14, 'La Ronde Carla-Bayle - Etape 3', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-06-09 12:38:23.616000', 'FSGT', 2, '09130', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (15, 'La Ronde Carla-Bayle - Etape 3', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-06-09 12:38:23.616000', 'FSGT', 2, '09130', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (16, 'Grand Prix de Larra', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-06-16 12:38:23.616000', 'FSGT', 2, '31330', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (17, 'Candie Acte 1', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-06-19 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (18, 'Grand Prix de Noueilles', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-06-23 12:38:23.616000', 'FSGT', 2, '31450', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (19, 'Candie Acte 2', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-06-27 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (20, 'Candie Acte 3', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-07-03 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (21, 'Grand Prix de Merles', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-07-07 12:38:23.616000', 'FSGT', 2, '82210', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (22, 'Candie Acte 4', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-07-10 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (23, 'Grand Prix de Tournefeuille', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-07-13 12:38:23.616000', 'FSGT', 2, '31170', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (24, 'Candie Acte 6', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-07-31 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (25, 'Candie Acte 7', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-08-07 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (26, 'Candie Acte 8', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-08-14 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (27, 'Grand Prix de Saint-Caprais', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-08-18 12:38:23.616000', 'FSGT', 2, '32200', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (28, 'Candie Acte 9', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-08-21 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (29, 'Saint-Anatoly', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-08-25 12:38:23.616000', 'FSGT', 2, '31570', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (30, 'Candie Acte 10', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-08-28 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (31, 'Trophée du Canton à Roquettes', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-09-01 12:38:23.616000', 'FSGT', 2, '31120', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (32, 'La Candie Race', '4eme,5eme,Feminines', '2019-09-04 12:38:23.616000', 'FSGT', 2, '31000', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '4,5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (33, 'Villemur', '1ere,2eme,3eme,4eme,5eme,Feminines', '2019-09-07 12:38:23.616000', 'FSGT', 2, '31340', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3,4/5');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (34, 'Grand Prix de Pins-Justaret', '1ere,2eme,3eme', '2019-09-08 12:38:23.616000', 'FSGT', 2, '31860', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (35, 'Grand Prix de Balma', '1ere,2eme,3eme', '2019-09-15 12:38:23.616000', 'FSGT', 2, '31130', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (36, 'Grand Prix de Paulhac', '1ere,2eme,3eme', '2019-09-22 12:38:23.616000', 'FSGT', 2, '31380', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3');
INSERT INTO public.competition (id, name, "categories", "eventDate", fede, "clubId", "zipCode", "info", observations, pricing, "races") VALUES (37, 'Grand Prix de Villariès', '1ere,2eme,3eme', '2019-09-29 12:38:23.616000', 'FSGT', 2, '31380', 'Circuit plat', 'Epreuve ouverte aux catégories de valeurs renseignées ci-dessus, disputée sous les règlements cyclistes
', '{"tarifName":"FSGT","tarif":10}', '1/2/3');



