name: Deploy on server
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Environnement
        options:
          - PROD
          - PREPROD
          - TEST
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            whoami
            docker ps
