name: Build Images and publish
on:
  workflow_run:
    workflows: ["Release OD"]
    types:
      - completed
jobs:
  build-opendossard:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v1
      - name: Build and deploy images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{github.repository_owner}}/opendossard_api_webapp:latest
