name: Docker Image CI

on: [push]

jobs:

build:

runs-on: ubuntu-latest
env:

steps:
- uses: actions/checkout@v1
- name: Build the docker-compose stack
run: docker-compose -f docker-compose.prod.yml up --build -d
- name: Sleep
uses: jakejarvis/wait-action@master
with:
time: '120s'
- name: Check running containers
run: docker ps
- name: Run test suite
run: wget https://localhost
