/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Open Dossard
 * Documentation de l'API Open Dossard
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface ClubEntity
 */
export interface ClubEntity {
    /**
     * 
     * @type {number}
     * @memberof ClubEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ClubEntity
     */
    shortName: string;
    /**
     * 
     * @type {string}
     * @memberof ClubEntity
     */
    dept: string;
    /**
     * 
     * @type {string}
     * @memberof ClubEntity
     */
    longName: string;
}

/**
 * 
 * @export
 * @interface ClubRow
 */
export interface ClubRow {
    /**
     * 
     * @type {number}
     * @memberof ClubRow
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClubRow
     */
    longName?: string;
    /**
     * 
     * @type {string}
     * @memberof ClubRow
     */
    dept?: string;
    /**
     * 
     * @type {string}
     * @memberof ClubRow
     */
    shortName?: string;
}

/**
 * 
 * @export
 * @interface CompetitionEntity
 */
export interface CompetitionEntity {
    /**
     * 
     * @type {number}
     * @memberof CompetitionEntity
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CompetitionEntity
     */
    eventDate: Date;
    /**
     * 
     * @type {ClubEntity}
     * @memberof CompetitionEntity
     */
    club: ClubEntity;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    zipCode: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    info?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionEntity
     */
    categories: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    observations?: string;
    /**
     * 
     * @type {any}
     * @memberof CompetitionEntity
     */
    pricing?: any;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionEntity
     */
    races?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    fede: string;
    /**
     * 
     * @type {string}
     * @memberof CompetitionEntity
     */
    competitionType?: string;
}

/**
 * 
 * @export
 * @interface CompetitionReorganize
 */
export interface CompetitionReorganize {
    /**
     * 
     * @type {number}
     * @memberof CompetitionReorganize
     */
    competitionId?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompetitionReorganize
     */
    races?: Array<string>;
}

/**
 * 
 * @export
 * @interface Filter
 */
export interface Filter {
    /**
     * 
     * @type {string}
     * @memberof Filter
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Filter
     */
    value?: string;
}

/**
 * 
 * @export
 * @interface LicenceEntity
 */
export interface LicenceEntity {
    /**
     * 
     * @type {number}
     * @memberof LicenceEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    licenceNumber: string;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    gender: string;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    club: string;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    dept: string;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    birthYear: string;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    catea: string;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    catev: string;
    /**
     * 
     * @type {string}
     * @memberof LicenceEntity
     */
    fede: string;
}

/**
 * 
 * @export
 * @interface LicencesPage
 */
export interface LicencesPage {
    /**
     * 
     * @type {Array<LicenceEntity>}
     * @memberof LicencesPage
     */
    data?: Array<LicenceEntity>;
    /**
     * 
     * @type {number}
     * @memberof LicencesPage
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof LicencesPage
     */
    totalCount?: number;
}

/**
 * 
 * @export
 * @interface RaceCreate
 */
export interface RaceCreate {
    /**
     * 
     * @type {number}
     * @memberof RaceCreate
     */
    competitionId?: number;
    /**
     * 
     * @type {number}
     * @memberof RaceCreate
     */
    licenceId?: number;
    /**
     * 
     * @type {number}
     * @memberof RaceCreate
     */
    riderNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof RaceCreate
     */
    raceCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceCreate
     */
    catev?: string;
}

/**
 * 
 * @export
 * @interface RaceNbRider
 */
export interface RaceNbRider {
    /**
     * 
     * @type {number}
     * @memberof RaceNbRider
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof RaceNbRider
     */
    raceCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceNbRider
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof RaceNbRider
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof RaceNbRider
     */
    fede?: string;
}

/**
 * 
 * @export
 * @interface RaceRow
 */
export interface RaceRow {
    /**
     * 
     * @type {number}
     * @memberof RaceRow
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    raceCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    birthYear?: string;
    /**
     * 
     * @type {number}
     * @memberof RaceRow
     */
    riderNumber?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RaceRow
     */
    surclassed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    licenceNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    club?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    catev?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    catea?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    fede?: string;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    gender?: string;
    /**
     * 
     * @type {number}
     * @memberof RaceRow
     */
    rankingScratch?: number;
    /**
     * 
     * @type {string}
     * @memberof RaceRow
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof RaceRow
     */
    competitionId: number;
    /**
     * 
     * @type {boolean}
     * @memberof RaceRow
     */
    sprintchallenge?: boolean;
}

/**
 * 
 * @export
 * @interface Search
 */
export interface Search {
    /**
     * 
     * @type {number}
     * @memberof Search
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof Search
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof Search
     */
    orderDirection?: string;
    /**
     * 
     * @type {string}
     * @memberof Search
     */
    orderBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Search
     */
    search?: string;
    /**
     * 
     * @type {Array<Filter>}
     * @memberof Search
     */
    filters?: Array<Filter>;
}

/**
 * 
 * @export
 * @interface UserEntity
 */
export interface UserEntity {
    /**
     * 
     * @type {number}
     * @memberof UserEntity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    accessToken?: string;
}


/**
 * AuthAPIApi - fetch parameter creator
 * @export
 */
export const AuthAPIApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * description
         * @summary Login utilisateur
         * @param {UserEntity} userEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(userEntity: UserEntity, options: any = {}): FetchArgs {
            // verify required parameter 'userEntity' is not null or undefined
            if (userEntity === null || userEntity === undefined) {
                throw new RequiredError('userEntity','Required parameter userEntity was null or undefined when calling login.');
            }
            const localVarPath = `/api/auth/login`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"UserEntity" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(userEntity || {}) : (userEntity || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Renvoie l'identifiant courant
         * @summary identifiant courant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        me(options: any = {}): FetchArgs {
            const localVarPath = `/api/auth/me`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthAPIApi - functional programming interface
 * @export
 */
export const AuthAPIApiFp = function(configuration?: Configuration) {
    return {
        /**
         * description
         * @summary Login utilisateur
         * @param {UserEntity} userEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(userEntity: UserEntity, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<UserEntity> {
            const localVarFetchArgs = AuthAPIApiFetchParamCreator(configuration).login(userEntity, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Renvoie l'identifiant courant
         * @summary identifiant courant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        me(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<UserEntity> {
            const localVarFetchArgs = AuthAPIApiFetchParamCreator(configuration).me(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * AuthAPIApi - factory interface
 * @export
 */
export const AuthAPIApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * description
         * @summary Login utilisateur
         * @param {UserEntity} userEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(userEntity: UserEntity, options?: any) {
            return AuthAPIApiFp(configuration).login(userEntity, options)(fetch, basePath);
        },
        /**
         * Renvoie l'identifiant courant
         * @summary identifiant courant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        me(options?: any) {
            return AuthAPIApiFp(configuration).me(options)(fetch, basePath);
        },
    };
};

/**
 * AuthAPIApi - object-oriented interface
 * @export
 * @class AuthAPIApi
 * @extends {BaseAPI}
 */
export class AuthAPIApi extends BaseAPI {
    /**
     * description
     * @summary Login utilisateur
     * @param {UserEntity} userEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthAPIApi
     */
    public login(userEntity: UserEntity, options?: any) {
        return AuthAPIApiFp(this.configuration).login(userEntity, options)(this.fetch, this.basePath);
    }

    /**
     * Renvoie l'identifiant courant
     * @summary identifiant courant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthAPIApi
     */
    public me(options?: any) {
        return AuthAPIApiFp(this.configuration).me(options)(this.fetch, this.basePath);
    }

}

/**
 * ClubAPIApi - fetch parameter creator
 * @export
 */
export const ClubAPIApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Renvoie la liste de tous les clubs sportifs
         * @summary Rechercher tous les clubs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllClubs(options: any = {}): FetchArgs {
            const localVarPath = `/api/clubs`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ClubAPIApi - functional programming interface
 * @export
 */
export const ClubAPIApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Renvoie la liste de tous les clubs sportifs
         * @summary Rechercher tous les clubs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllClubs(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<ClubRow>> {
            const localVarFetchArgs = ClubAPIApiFetchParamCreator(configuration).getAllClubs(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ClubAPIApi - factory interface
 * @export
 */
export const ClubAPIApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Renvoie la liste de tous les clubs sportifs
         * @summary Rechercher tous les clubs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllClubs(options?: any) {
            return ClubAPIApiFp(configuration).getAllClubs(options)(fetch, basePath);
        },
    };
};

/**
 * ClubAPIApi - object-oriented interface
 * @export
 * @class ClubAPIApi
 * @extends {BaseAPI}
 */
export class ClubAPIApi extends BaseAPI {
    /**
     * Renvoie la liste de tous les clubs sportifs
     * @summary Rechercher tous les clubs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClubAPIApi
     */
    public getAllClubs(options?: any) {
        return ClubAPIApiFp(this.configuration).getAllClubs(options)(this.fetch, this.basePath);
    }

}

/**
 * CompetitionAPIApi - fetch parameter creator
 * @export
 */
export const CompetitionAPIApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Recherche une épreuve par son identifiant
         * @summary Recherche d'une épreuve par ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(id: string, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling get.');
            }
            const localVarPath = `/api/competition/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Recherche toutes les compétitions disponibles
         * @summary Rechercher Toutes les compétitions 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCompetitions(options: any = {}): FetchArgs {
            const localVarPath = `/api/competition`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Réorganisation des courses
         * @param {CompetitionReorganize} competitionReorganize 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reorganize(competitionReorganize: CompetitionReorganize, options: any = {}): FetchArgs {
            // verify required parameter 'competitionReorganize' is not null or undefined
            if (competitionReorganize === null || competitionReorganize === undefined) {
                throw new RequiredError('competitionReorganize','Required parameter competitionReorganize was null or undefined when calling reorganize.');
            }
            const localVarPath = `/api/competition/reorganize`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CompetitionReorganize" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(competitionReorganize || {}) : (competitionReorganize || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CompetitionAPIApi - functional programming interface
 * @export
 */
export const CompetitionAPIApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Recherche une épreuve par son identifiant
         * @summary Recherche d'une épreuve par ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<CompetitionEntity> {
            const localVarFetchArgs = CompetitionAPIApiFetchParamCreator(configuration).get(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Recherche toutes les compétitions disponibles
         * @summary Rechercher Toutes les compétitions 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCompetitions(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<CompetitionEntity>> {
            const localVarFetchArgs = CompetitionAPIApiFetchParamCreator(configuration).getAllCompetitions(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Réorganisation des courses
         * @param {CompetitionReorganize} competitionReorganize 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reorganize(competitionReorganize: CompetitionReorganize, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = CompetitionAPIApiFetchParamCreator(configuration).reorganize(competitionReorganize, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * CompetitionAPIApi - factory interface
 * @export
 */
export const CompetitionAPIApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Recherche une épreuve par son identifiant
         * @summary Recherche d'une épreuve par ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(id: string, options?: any) {
            return CompetitionAPIApiFp(configuration).get(id, options)(fetch, basePath);
        },
        /**
         * Recherche toutes les compétitions disponibles
         * @summary Rechercher Toutes les compétitions 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCompetitions(options?: any) {
            return CompetitionAPIApiFp(configuration).getAllCompetitions(options)(fetch, basePath);
        },
        /**
         * 
         * @summary Réorganisation des courses
         * @param {CompetitionReorganize} competitionReorganize 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reorganize(competitionReorganize: CompetitionReorganize, options?: any) {
            return CompetitionAPIApiFp(configuration).reorganize(competitionReorganize, options)(fetch, basePath);
        },
    };
};

/**
 * CompetitionAPIApi - object-oriented interface
 * @export
 * @class CompetitionAPIApi
 * @extends {BaseAPI}
 */
export class CompetitionAPIApi extends BaseAPI {
    /**
     * Recherche une épreuve par son identifiant
     * @summary Recherche d'une épreuve par ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompetitionAPIApi
     */
    public get(id: string, options?: any) {
        return CompetitionAPIApiFp(this.configuration).get(id, options)(this.fetch, this.basePath);
    }

    /**
     * Recherche toutes les compétitions disponibles
     * @summary Rechercher Toutes les compétitions 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompetitionAPIApi
     */
    public getAllCompetitions(options?: any) {
        return CompetitionAPIApiFp(this.configuration).getAllCompetitions(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Réorganisation des courses
     * @param {CompetitionReorganize} competitionReorganize 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompetitionAPIApi
     */
    public reorganize(competitionReorganize: CompetitionReorganize, options?: any) {
        return CompetitionAPIApiFp(this.configuration).reorganize(competitionReorganize, options)(this.fetch, this.basePath);
    }

}

/**
 * LicenceAPIApi - fetch parameter creator
 * @export
 */
export const LicenceAPIApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Supprime une licence
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: string, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling _delete.');
            }
            const localVarPath = `/api/licences/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cree une nouvelle licence
         * @param {LicenceEntity} licenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(licenceEntity: LicenceEntity, options: any = {}): FetchArgs {
            // verify required parameter 'licenceEntity' is not null or undefined
            if (licenceEntity === null || licenceEntity === undefined) {
                throw new RequiredError('licenceEntity','Required parameter licenceEntity was null or undefined when calling create.');
            }
            const localVarPath = `/api/licences`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"LicenceEntity" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(licenceEntity || {}) : (licenceEntity || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Recherche une licence par son identifiant
         * @summary Rechercher une licence par ID 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(id: string, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling get.');
            }
            const localVarPath = `/api/licences/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Renvoie toutes les licences
         * @summary Rechercher toutes les licences 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLicences(options: any = {}): FetchArgs {
            const localVarPath = `/api/licences`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Rechercher des licences en fonction, du nom, prénom ou numéro de licence 
         * @summary Recherche des licences
         * @param {string} param 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLicencesLike(param: string, options: any = {}): FetchArgs {
            // verify required parameter 'param' is not null or undefined
            if (param === null || param === undefined) {
                throw new RequiredError('param','Required parameter param was null or undefined when calling getLicencesLike.');
            }
            const localVarPath = `/api/licences/search/{param}`
                .replace(`{${"param"}}`, encodeURIComponent(String(param)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Recherche paginée utilisant currentPage, pageSize, orderDirection, orderBy et Filters
         * @summary Rechercher par page les licences 
         * @param {Search} search 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPageSizeLicencesForPage(search: Search, options: any = {}): FetchArgs {
            // verify required parameter 'search' is not null or undefined
            if (search === null || search === undefined) {
                throw new RequiredError('search','Required parameter search was null or undefined when calling getPageSizeLicencesForPage.');
            }
            const localVarPath = `/api/licences/filter`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"Search" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(search || {}) : (search || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Met à jour une licence existante
         * @param {LicenceEntity} licenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(licenceEntity: LicenceEntity, options: any = {}): FetchArgs {
            // verify required parameter 'licenceEntity' is not null or undefined
            if (licenceEntity === null || licenceEntity === undefined) {
                throw new RequiredError('licenceEntity','Required parameter licenceEntity was null or undefined when calling update.');
            }
            const localVarPath = `/api/licences`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"LicenceEntity" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(licenceEntity || {}) : (licenceEntity || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LicenceAPIApi - functional programming interface
 * @export
 */
export const LicenceAPIApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Supprime une licence
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = LicenceAPIApiFetchParamCreator(configuration)._delete(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Cree une nouvelle licence
         * @param {LicenceEntity} licenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(licenceEntity: LicenceEntity, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = LicenceAPIApiFetchParamCreator(configuration).create(licenceEntity, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Recherche une licence par son identifiant
         * @summary Rechercher une licence par ID 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<LicenceEntity> {
            const localVarFetchArgs = LicenceAPIApiFetchParamCreator(configuration).get(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Renvoie toutes les licences
         * @summary Rechercher toutes les licences 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLicences(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<LicenceEntity>> {
            const localVarFetchArgs = LicenceAPIApiFetchParamCreator(configuration).getAllLicences(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Rechercher des licences en fonction, du nom, prénom ou numéro de licence 
         * @summary Recherche des licences
         * @param {string} param 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLicencesLike(param: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<LicenceEntity>> {
            const localVarFetchArgs = LicenceAPIApiFetchParamCreator(configuration).getLicencesLike(param, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Recherche paginée utilisant currentPage, pageSize, orderDirection, orderBy et Filters
         * @summary Rechercher par page les licences 
         * @param {Search} search 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPageSizeLicencesForPage(search: Search, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<LicencesPage> {
            const localVarFetchArgs = LicenceAPIApiFetchParamCreator(configuration).getPageSizeLicencesForPage(search, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Met à jour une licence existante
         * @param {LicenceEntity} licenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(licenceEntity: LicenceEntity, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = LicenceAPIApiFetchParamCreator(configuration).update(licenceEntity, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * LicenceAPIApi - factory interface
 * @export
 */
export const LicenceAPIApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Supprime une licence
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: string, options?: any) {
            return LicenceAPIApiFp(configuration)._delete(id, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Cree une nouvelle licence
         * @param {LicenceEntity} licenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(licenceEntity: LicenceEntity, options?: any) {
            return LicenceAPIApiFp(configuration).create(licenceEntity, options)(fetch, basePath);
        },
        /**
         * Recherche une licence par son identifiant
         * @summary Rechercher une licence par ID 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(id: string, options?: any) {
            return LicenceAPIApiFp(configuration).get(id, options)(fetch, basePath);
        },
        /**
         * Renvoie toutes les licences
         * @summary Rechercher toutes les licences 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLicences(options?: any) {
            return LicenceAPIApiFp(configuration).getAllLicences(options)(fetch, basePath);
        },
        /**
         * Rechercher des licences en fonction, du nom, prénom ou numéro de licence 
         * @summary Recherche des licences
         * @param {string} param 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLicencesLike(param: string, options?: any) {
            return LicenceAPIApiFp(configuration).getLicencesLike(param, options)(fetch, basePath);
        },
        /**
         * Recherche paginée utilisant currentPage, pageSize, orderDirection, orderBy et Filters
         * @summary Rechercher par page les licences 
         * @param {Search} search 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPageSizeLicencesForPage(search: Search, options?: any) {
            return LicenceAPIApiFp(configuration).getPageSizeLicencesForPage(search, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Met à jour une licence existante
         * @param {LicenceEntity} licenceEntity 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(licenceEntity: LicenceEntity, options?: any) {
            return LicenceAPIApiFp(configuration).update(licenceEntity, options)(fetch, basePath);
        },
    };
};

/**
 * LicenceAPIApi - object-oriented interface
 * @export
 * @class LicenceAPIApi
 * @extends {BaseAPI}
 */
export class LicenceAPIApi extends BaseAPI {
    /**
     * 
     * @summary Supprime une licence
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicenceAPIApi
     */
    public _delete(id: string, options?: any) {
        return LicenceAPIApiFp(this.configuration)._delete(id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Cree une nouvelle licence
     * @param {LicenceEntity} licenceEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicenceAPIApi
     */
    public create(licenceEntity: LicenceEntity, options?: any) {
        return LicenceAPIApiFp(this.configuration).create(licenceEntity, options)(this.fetch, this.basePath);
    }

    /**
     * Recherche une licence par son identifiant
     * @summary Rechercher une licence par ID 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicenceAPIApi
     */
    public get(id: string, options?: any) {
        return LicenceAPIApiFp(this.configuration).get(id, options)(this.fetch, this.basePath);
    }

    /**
     * Renvoie toutes les licences
     * @summary Rechercher toutes les licences 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicenceAPIApi
     */
    public getAllLicences(options?: any) {
        return LicenceAPIApiFp(this.configuration).getAllLicences(options)(this.fetch, this.basePath);
    }

    /**
     * Rechercher des licences en fonction, du nom, prénom ou numéro de licence 
     * @summary Recherche des licences
     * @param {string} param 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicenceAPIApi
     */
    public getLicencesLike(param: string, options?: any) {
        return LicenceAPIApiFp(this.configuration).getLicencesLike(param, options)(this.fetch, this.basePath);
    }

    /**
     * Recherche paginée utilisant currentPage, pageSize, orderDirection, orderBy et Filters
     * @summary Rechercher par page les licences 
     * @param {Search} search 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicenceAPIApi
     */
    public getPageSizeLicencesForPage(search: Search, options?: any) {
        return LicenceAPIApiFp(this.configuration).getPageSizeLicencesForPage(search, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Met à jour une licence existante
     * @param {LicenceEntity} licenceEntity 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicenceAPIApi
     */
    public update(licenceEntity: LicenceEntity, options?: any) {
        return LicenceAPIApiFp(this.configuration).update(licenceEntity, options)(this.fetch, this.basePath);
    }

}

/**
 * RaceAPIApi - fetch parameter creator
 * @export
 */
export const RaceAPIApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Supprime une course
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: string, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling _delete.');
            }
            const localVarPath = `/api/races/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cree une nouvelle course 
         * @param {RaceCreate} raceCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(raceCreate: RaceCreate, options: any = {}): FetchArgs {
            // verify required parameter 'raceCreate' is not null or undefined
            if (raceCreate === null || raceCreate === undefined) {
                throw new RequiredError('raceCreate','Required parameter raceCreate was null or undefined when calling create.');
            }
            const localVarPath = `/api/races`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"RaceCreate" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(raceCreate || {}) : (raceCreate || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Classe le vainqueur du challenge
         * @param {RaceRow} raceRow 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        flagChallenge(raceRow: RaceRow, options: any = {}): FetchArgs {
            // verify required parameter 'raceRow' is not null or undefined
            if (raceRow === null || raceRow === undefined) {
                throw new RequiredError('raceRow','Required parameter raceRow was null or undefined when calling flagChallenge.');
            }
            const localVarPath = `/api/races/flagChallenge`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"RaceRow" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(raceRow || {}) : (raceRow || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Rechercher tous les coureurs participants à une course 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCompetitionRaces(id: number, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getCompetitionRaces.');
            }
            const localVarPath = `/api/races/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Rechercher le nombre de coureur par course 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNumberRider(options: any = {}): FetchArgs {
            const localVarPath = `/api/races/nbRider`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Supprime un coureur du classement
         * @param {RaceRow} raceRow 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeRanking(raceRow: RaceRow, options: any = {}): FetchArgs {
            // verify required parameter 'raceRow' is not null or undefined
            if (raceRow === null || raceRow === undefined) {
                throw new RequiredError('raceRow','Required parameter raceRow was null or undefined when calling removeRanking.');
            }
            const localVarPath = `/api/races/removeRanking`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"RaceRow" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(raceRow || {}) : (raceRow || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Réordonne le classement
         * @param {Array<RaceRow>} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reorderRanking(body: Array<RaceRow>, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling reorderRanking.');
            }
            const localVarPath = `/api/races/reorderRank`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"Array&lt;RaceRow&gt;" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Met à jour le classement du coureur 
         * @param {RaceRow} raceRow 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(raceRow: RaceRow, options: any = {}): FetchArgs {
            // verify required parameter 'raceRow' is not null or undefined
            if (raceRow === null || raceRow === undefined) {
                throw new RequiredError('raceRow','Required parameter raceRow was null or undefined when calling update.');
            }
            const localVarPath = `/api/races/update`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"RaceRow" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(raceRow || {}) : (raceRow || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RaceAPIApi - functional programming interface
 * @export
 */
export const RaceAPIApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Supprime une course
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = RaceAPIApiFetchParamCreator(configuration)._delete(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Cree une nouvelle course 
         * @param {RaceCreate} raceCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(raceCreate: RaceCreate, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = RaceAPIApiFetchParamCreator(configuration).create(raceCreate, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Classe le vainqueur du challenge
         * @param {RaceRow} raceRow 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        flagChallenge(raceRow: RaceRow, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = RaceAPIApiFetchParamCreator(configuration).flagChallenge(raceRow, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Rechercher tous les coureurs participants à une course 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCompetitionRaces(id: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<RaceRow>> {
            const localVarFetchArgs = RaceAPIApiFetchParamCreator(configuration).getCompetitionRaces(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Rechercher le nombre de coureur par course 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNumberRider(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<RaceNbRider>> {
            const localVarFetchArgs = RaceAPIApiFetchParamCreator(configuration).getNumberRider(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Supprime un coureur du classement
         * @param {RaceRow} raceRow 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeRanking(raceRow: RaceRow, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = RaceAPIApiFetchParamCreator(configuration).removeRanking(raceRow, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Réordonne le classement
         * @param {Array<RaceRow>} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reorderRanking(body: Array<RaceRow>, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = RaceAPIApiFetchParamCreator(configuration).reorderRanking(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Met à jour le classement du coureur 
         * @param {RaceRow} raceRow 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(raceRow: RaceRow, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = RaceAPIApiFetchParamCreator(configuration).update(raceRow, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * RaceAPIApi - factory interface
 * @export
 */
export const RaceAPIApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Supprime une course
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: string, options?: any) {
            return RaceAPIApiFp(configuration)._delete(id, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Cree une nouvelle course 
         * @param {RaceCreate} raceCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(raceCreate: RaceCreate, options?: any) {
            return RaceAPIApiFp(configuration).create(raceCreate, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Classe le vainqueur du challenge
         * @param {RaceRow} raceRow 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        flagChallenge(raceRow: RaceRow, options?: any) {
            return RaceAPIApiFp(configuration).flagChallenge(raceRow, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Rechercher tous les coureurs participants à une course 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCompetitionRaces(id: number, options?: any) {
            return RaceAPIApiFp(configuration).getCompetitionRaces(id, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Rechercher le nombre de coureur par course 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNumberRider(options?: any) {
            return RaceAPIApiFp(configuration).getNumberRider(options)(fetch, basePath);
        },
        /**
         * 
         * @summary Supprime un coureur du classement
         * @param {RaceRow} raceRow 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeRanking(raceRow: RaceRow, options?: any) {
            return RaceAPIApiFp(configuration).removeRanking(raceRow, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Réordonne le classement
         * @param {Array<RaceRow>} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reorderRanking(body: Array<RaceRow>, options?: any) {
            return RaceAPIApiFp(configuration).reorderRanking(body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Met à jour le classement du coureur 
         * @param {RaceRow} raceRow 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(raceRow: RaceRow, options?: any) {
            return RaceAPIApiFp(configuration).update(raceRow, options)(fetch, basePath);
        },
    };
};

/**
 * RaceAPIApi - object-oriented interface
 * @export
 * @class RaceAPIApi
 * @extends {BaseAPI}
 */
export class RaceAPIApi extends BaseAPI {
    /**
     * 
     * @summary Supprime une course
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RaceAPIApi
     */
    public _delete(id: string, options?: any) {
        return RaceAPIApiFp(this.configuration)._delete(id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Cree une nouvelle course 
     * @param {RaceCreate} raceCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RaceAPIApi
     */
    public create(raceCreate: RaceCreate, options?: any) {
        return RaceAPIApiFp(this.configuration).create(raceCreate, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Classe le vainqueur du challenge
     * @param {RaceRow} raceRow 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RaceAPIApi
     */
    public flagChallenge(raceRow: RaceRow, options?: any) {
        return RaceAPIApiFp(this.configuration).flagChallenge(raceRow, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Rechercher tous les coureurs participants à une course 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RaceAPIApi
     */
    public getCompetitionRaces(id: number, options?: any) {
        return RaceAPIApiFp(this.configuration).getCompetitionRaces(id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Rechercher le nombre de coureur par course 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RaceAPIApi
     */
    public getNumberRider(options?: any) {
        return RaceAPIApiFp(this.configuration).getNumberRider(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Supprime un coureur du classement
     * @param {RaceRow} raceRow 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RaceAPIApi
     */
    public removeRanking(raceRow: RaceRow, options?: any) {
        return RaceAPIApiFp(this.configuration).removeRanking(raceRow, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Réordonne le classement
     * @param {Array<RaceRow>} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RaceAPIApi
     */
    public reorderRanking(body: Array<RaceRow>, options?: any) {
        return RaceAPIApiFp(this.configuration).reorderRanking(body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Met à jour le classement du coureur 
     * @param {RaceRow} raceRow 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RaceAPIApi
     */
    public update(raceRow: RaceRow, options?: any) {
        return RaceAPIApiFp(this.configuration).update(raceRow, options)(this.fetch, this.basePath);
    }

}

