/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface CalendarsCtrlRemovePayload
 */
export interface CalendarsCtrlRemovePayload {
    /**
     * 
     * @type {string}
     * @memberof CalendarsCtrlRemovePayload
     */
    id: string;
}

/**
 * 
 * @export
 * @interface CalendarsCtrlSavePayload
 */
export interface CalendarsCtrlSavePayload {
    /**
     * 
     * @type {string}
     * @memberof CalendarsCtrlSavePayload
     */
    name?: string;
}

/**
 * 
 * @export
 * @interface CalendarsCtrlUpdatePayload
 */
export interface CalendarsCtrlUpdatePayload {
    /**
     * 
     * @type {string}
     * @memberof CalendarsCtrlUpdatePayload
     */
    name: string;
}

/**
 * 
 * @export
 * @interface EventsCtrlSavePayload
 */
export interface EventsCtrlSavePayload {
    /**
     * 
     * @type {string}
     * @memberof EventsCtrlSavePayload
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsCtrlSavePayload
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsCtrlSavePayload
     */
    name?: string;
}

/**
 * 
 * @export
 * @interface EventsCtrlUpdatePayload
 */
export interface EventsCtrlUpdatePayload {
    /**
     * 
     * @type {string}
     * @memberof EventsCtrlUpdatePayload
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsCtrlUpdatePayload
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EventsCtrlUpdatePayload
     */
    name?: string;
}

/**
 * 
 * @export
 * @interface Licence
 */
export interface Licence {
    /**
     * 
     * @type {number}
     * @memberof Licence
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Licence
     */
    licenceNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Licence
     */
    nom?: string;
    /**
     * 
     * @type {string}
     * @memberof Licence
     */
    prenom?: string;
    /**
     * 
     * @type {string}
     * @memberof Licence
     */
    genre?: string;
    /**
     * 
     * @type {string}
     * @memberof Licence
     */
    club?: string;
    /**
     * 
     * @type {string}
     * @memberof Licence
     */
    dept?: string;
    /**
     * 
     * @type {string}
     * @memberof Licence
     */
    age?: string;
    /**
     * 
     * @type {string}
     * @memberof Licence
     */
    catea?: string;
    /**
     * 
     * @type {string}
     * @memberof Licence
     */
    catev?: string;
    /**
     * 
     * @type {any}
     * @memberof Licence
     */
    fede?: any;
}

/**
 * 
 * @export
 * @interface LicencesCtrlSavePayload
 */
export interface LicencesCtrlSavePayload {
    /**
     * 
     * @type {string}
     * @memberof LicencesCtrlSavePayload
     */
    licenceNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof LicencesCtrlSavePayload
     */
    nom?: string;
    /**
     * 
     * @type {string}
     * @memberof LicencesCtrlSavePayload
     */
    prenom?: string;
    /**
     * 
     * @type {string}
     * @memberof LicencesCtrlSavePayload
     */
    genre?: string;
}


/**
 * CalendarsCtrlApi - fetch parameter creator
 * @export
 */
export const CalendarsCtrlApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlGet(id: string, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling calendarsCtrlGet.');
            }
            const localVarPath = `/api/calendars/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlGetAllCalendars(options: any = {}): FetchArgs {
            const localVarPath = `/api/calendars`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlRemove(options: any = {}): FetchArgs {
            const localVarPath = `/api/calendars`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlSave(options: any = {}): FetchArgs {
            const localVarPath = `/api/calendars`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlUpdate(id: string, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling calendarsCtrlUpdate.');
            }
            const localVarPath = `/api/calendars/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CalendarsCtrlApi - functional programming interface
 * @export
 */
export const CalendarsCtrlApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlGet(id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = CalendarsCtrlApiFetchParamCreator(configuration).calendarsCtrlGet(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlGetAllCalendars(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = CalendarsCtrlApiFetchParamCreator(configuration).calendarsCtrlGetAllCalendars(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlRemove(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = CalendarsCtrlApiFetchParamCreator(configuration).calendarsCtrlRemove(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlSave(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = CalendarsCtrlApiFetchParamCreator(configuration).calendarsCtrlSave(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlUpdate(id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = CalendarsCtrlApiFetchParamCreator(configuration).calendarsCtrlUpdate(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * CalendarsCtrlApi - factory interface
 * @export
 */
export const CalendarsCtrlApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlGet(id: string, options?: any) {
            return CalendarsCtrlApiFp(configuration).calendarsCtrlGet(id, options)(fetch, basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlGetAllCalendars(options?: any) {
            return CalendarsCtrlApiFp(configuration).calendarsCtrlGetAllCalendars(options)(fetch, basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlRemove(options?: any) {
            return CalendarsCtrlApiFp(configuration).calendarsCtrlRemove(options)(fetch, basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlSave(options?: any) {
            return CalendarsCtrlApiFp(configuration).calendarsCtrlSave(options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarsCtrlUpdate(id: string, options?: any) {
            return CalendarsCtrlApiFp(configuration).calendarsCtrlUpdate(id, options)(fetch, basePath);
        },
    };
};

/**
 * CalendarsCtrlApi - object-oriented interface
 * @export
 * @class CalendarsCtrlApi
 * @extends {BaseAPI}
 */
export class CalendarsCtrlApi extends BaseAPI {
    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarsCtrlApi
     */
    public calendarsCtrlGet(id: string, options?: any) {
        return CalendarsCtrlApiFp(this.configuration).calendarsCtrlGet(id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarsCtrlApi
     */
    public calendarsCtrlGetAllCalendars(options?: any) {
        return CalendarsCtrlApiFp(this.configuration).calendarsCtrlGetAllCalendars(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarsCtrlApi
     */
    public calendarsCtrlRemove(options?: any) {
        return CalendarsCtrlApiFp(this.configuration).calendarsCtrlRemove(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarsCtrlApi
     */
    public calendarsCtrlSave(options?: any) {
        return CalendarsCtrlApiFp(this.configuration).calendarsCtrlSave(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarsCtrlApi
     */
    public calendarsCtrlUpdate(id: string, options?: any) {
        return CalendarsCtrlApiFp(this.configuration).calendarsCtrlUpdate(id, options)(this.fetch, this.basePath);
    }

}

/**
 * EventsCtrlApi - fetch parameter creator
 * @export
 */
export const EventsCtrlApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlGet(calendarId: string, id: string, options: any = {}): FetchArgs {
            // verify required parameter 'calendarId' is not null or undefined
            if (calendarId === null || calendarId === undefined) {
                throw new RequiredError('calendarId','Required parameter calendarId was null or undefined when calling eventsCtrlGet.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling eventsCtrlGet.');
            }
            const localVarPath = `/api/calendars/{calendarId}/events/{id}`
                .replace(`{${"calendarId"}}`, encodeURIComponent(String(calendarId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlGetLicences(calendarId: string, options: any = {}): FetchArgs {
            // verify required parameter 'calendarId' is not null or undefined
            if (calendarId === null || calendarId === undefined) {
                throw new RequiredError('calendarId','Required parameter calendarId was null or undefined when calling eventsCtrlGetLicences.');
            }
            const localVarPath = `/api/calendars/{calendarId}/events`
                .replace(`{${"calendarId"}}`, encodeURIComponent(String(calendarId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlGetTasks(calendarId: string, id: string, options: any = {}): FetchArgs {
            // verify required parameter 'calendarId' is not null or undefined
            if (calendarId === null || calendarId === undefined) {
                throw new RequiredError('calendarId','Required parameter calendarId was null or undefined when calling eventsCtrlGetTasks.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling eventsCtrlGetTasks.');
            }
            const localVarPath = `/api/calendars/{calendarId}/events/{id}/tasks`
                .replace(`{${"calendarId"}}`, encodeURIComponent(String(calendarId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlRemove(calendarId: string, id: string, options: any = {}): FetchArgs {
            // verify required parameter 'calendarId' is not null or undefined
            if (calendarId === null || calendarId === undefined) {
                throw new RequiredError('calendarId','Required parameter calendarId was null or undefined when calling eventsCtrlRemove.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling eventsCtrlRemove.');
            }
            const localVarPath = `/api/calendars/{calendarId}/events/{id}`
                .replace(`{${"calendarId"}}`, encodeURIComponent(String(calendarId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlSave(calendarId: string, options: any = {}): FetchArgs {
            // verify required parameter 'calendarId' is not null or undefined
            if (calendarId === null || calendarId === undefined) {
                throw new RequiredError('calendarId','Required parameter calendarId was null or undefined when calling eventsCtrlSave.');
            }
            const localVarPath = `/api/calendars/{calendarId}/events`
                .replace(`{${"calendarId"}}`, encodeURIComponent(String(calendarId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlUpdate(calendarId: string, id: string, options: any = {}): FetchArgs {
            // verify required parameter 'calendarId' is not null or undefined
            if (calendarId === null || calendarId === undefined) {
                throw new RequiredError('calendarId','Required parameter calendarId was null or undefined when calling eventsCtrlUpdate.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling eventsCtrlUpdate.');
            }
            const localVarPath = `/api/calendars/{calendarId}/events/{id}`
                .replace(`{${"calendarId"}}`, encodeURIComponent(String(calendarId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventsCtrlApi - functional programming interface
 * @export
 */
export const EventsCtrlApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlGet(calendarId: string, id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = EventsCtrlApiFetchParamCreator(configuration).eventsCtrlGet(calendarId, id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlGetLicences(calendarId: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = EventsCtrlApiFetchParamCreator(configuration).eventsCtrlGetLicences(calendarId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlGetTasks(calendarId: string, id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = EventsCtrlApiFetchParamCreator(configuration).eventsCtrlGetTasks(calendarId, id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlRemove(calendarId: string, id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = EventsCtrlApiFetchParamCreator(configuration).eventsCtrlRemove(calendarId, id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlSave(calendarId: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = EventsCtrlApiFetchParamCreator(configuration).eventsCtrlSave(calendarId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlUpdate(calendarId: string, id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = EventsCtrlApiFetchParamCreator(configuration).eventsCtrlUpdate(calendarId, id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * EventsCtrlApi - factory interface
 * @export
 */
export const EventsCtrlApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlGet(calendarId: string, id: string, options?: any) {
            return EventsCtrlApiFp(configuration).eventsCtrlGet(calendarId, id, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlGetLicences(calendarId: string, options?: any) {
            return EventsCtrlApiFp(configuration).eventsCtrlGetLicences(calendarId, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlGetTasks(calendarId: string, id: string, options?: any) {
            return EventsCtrlApiFp(configuration).eventsCtrlGetTasks(calendarId, id, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlRemove(calendarId: string, id: string, options?: any) {
            return EventsCtrlApiFp(configuration).eventsCtrlRemove(calendarId, id, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlSave(calendarId: string, options?: any) {
            return EventsCtrlApiFp(configuration).eventsCtrlSave(calendarId, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} calendarId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsCtrlUpdate(calendarId: string, id: string, options?: any) {
            return EventsCtrlApiFp(configuration).eventsCtrlUpdate(calendarId, id, options)(fetch, basePath);
        },
    };
};

/**
 * EventsCtrlApi - object-oriented interface
 * @export
 * @class EventsCtrlApi
 * @extends {BaseAPI}
 */
export class EventsCtrlApi extends BaseAPI {
    /**
     * 
     * @param {string} calendarId 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsCtrlApi
     */
    public eventsCtrlGet(calendarId: string, id: string, options?: any) {
        return EventsCtrlApiFp(this.configuration).eventsCtrlGet(calendarId, id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} calendarId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsCtrlApi
     */
    public eventsCtrlGetLicences(calendarId: string, options?: any) {
        return EventsCtrlApiFp(this.configuration).eventsCtrlGetLicences(calendarId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} calendarId 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsCtrlApi
     */
    public eventsCtrlGetTasks(calendarId: string, id: string, options?: any) {
        return EventsCtrlApiFp(this.configuration).eventsCtrlGetTasks(calendarId, id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} calendarId 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsCtrlApi
     */
    public eventsCtrlRemove(calendarId: string, id: string, options?: any) {
        return EventsCtrlApiFp(this.configuration).eventsCtrlRemove(calendarId, id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} calendarId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsCtrlApi
     */
    public eventsCtrlSave(calendarId: string, options?: any) {
        return EventsCtrlApiFp(this.configuration).eventsCtrlSave(calendarId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} calendarId 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsCtrlApi
     */
    public eventsCtrlUpdate(calendarId: string, id: string, options?: any) {
        return EventsCtrlApiFp(this.configuration).eventsCtrlUpdate(calendarId, id, options)(this.fetch, this.basePath);
    }

}

/**
 * LicencesCtrlApi - fetch parameter creator
 * @export
 */
export const LicencesCtrlApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        licencesCtrlGet(id: string, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling licencesCtrlGet.');
            }
            const localVarPath = `/api/licences/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        licencesCtrlGetAllLicences(options: any = {}): FetchArgs {
            const localVarPath = `/api/licences`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        licencesCtrlSave(options: any = {}): FetchArgs {
            const localVarPath = `/api/licences`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LicencesCtrlApi - functional programming interface
 * @export
 */
export const LicencesCtrlApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        licencesCtrlGet(id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = LicencesCtrlApiFetchParamCreator(configuration).licencesCtrlGet(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        licencesCtrlGetAllLicences(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Licence>> {
            const localVarFetchArgs = LicencesCtrlApiFetchParamCreator(configuration).licencesCtrlGetAllLicences(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        licencesCtrlSave(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = LicencesCtrlApiFetchParamCreator(configuration).licencesCtrlSave(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * LicencesCtrlApi - factory interface
 * @export
 */
export const LicencesCtrlApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        licencesCtrlGet(id: string, options?: any) {
            return LicencesCtrlApiFp(configuration).licencesCtrlGet(id, options)(fetch, basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        licencesCtrlGetAllLicences(options?: any) {
            return LicencesCtrlApiFp(configuration).licencesCtrlGetAllLicences(options)(fetch, basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        licencesCtrlSave(options?: any) {
            return LicencesCtrlApiFp(configuration).licencesCtrlSave(options)(fetch, basePath);
        },
    };
};

/**
 * LicencesCtrlApi - object-oriented interface
 * @export
 * @class LicencesCtrlApi
 * @extends {BaseAPI}
 */
export class LicencesCtrlApi extends BaseAPI {
    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicencesCtrlApi
     */
    public licencesCtrlGet(id: string, options?: any) {
        return LicencesCtrlApiFp(this.configuration).licencesCtrlGet(id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicencesCtrlApi
     */
    public licencesCtrlGetAllLicences(options?: any) {
        return LicencesCtrlApiFp(this.configuration).licencesCtrlGetAllLicences(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicencesCtrlApi
     */
    public licencesCtrlSave(options?: any) {
        return LicencesCtrlApiFp(this.configuration).licencesCtrlSave(options)(this.fetch, this.basePath);
    }

}

/**
 * RestCtrlApi - fetch parameter creator
 * @export
 */
export const RestCtrlApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restCtrlGetRoutes(options: any = {}): FetchArgs {
            const localVarPath = `/api`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RestCtrlApi - functional programming interface
 * @export
 */
export const RestCtrlApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restCtrlGetRoutes(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = RestCtrlApiFetchParamCreator(configuration).restCtrlGetRoutes(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * RestCtrlApi - factory interface
 * @export
 */
export const RestCtrlApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restCtrlGetRoutes(options?: any) {
            return RestCtrlApiFp(configuration).restCtrlGetRoutes(options)(fetch, basePath);
        },
    };
};

/**
 * RestCtrlApi - object-oriented interface
 * @export
 * @class RestCtrlApi
 * @extends {BaseAPI}
 */
export class RestCtrlApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RestCtrlApi
     */
    public restCtrlGetRoutes(options?: any) {
        return RestCtrlApiFp(this.configuration).restCtrlGetRoutes(options)(this.fetch, this.basePath);
    }

}

